// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var AnimatedRe$BsReactNativeWeb = require("./animatedRe.js");

var Animation = AnimatedRe$BsReactNativeWeb.Animation;

var CompositeAnimation = AnimatedRe$BsReactNativeWeb.CompositeAnimation;

var Easing = AnimatedRe$BsReactNativeWeb.Easing;

var Interpolation = AnimatedRe$BsReactNativeWeb.Interpolation;

var Value = AnimatedRe$BsReactNativeWeb.Value;

var ValueXY = AnimatedRe$BsReactNativeWeb.ValueXY;

var $$event = AnimatedRe$BsReactNativeWeb.$$event;

var delay = AnimatedRe$BsReactNativeWeb.delay;

var sequence = AnimatedRe$BsReactNativeWeb.sequence;

var parallel = AnimatedRe$BsReactNativeWeb.parallel;

var stagger = AnimatedRe$BsReactNativeWeb.stagger;

var loop = AnimatedRe$BsReactNativeWeb.loop;

var createAnimatedComponent = AnimatedRe$BsReactNativeWeb.createAnimatedComponent;

var Timing = AnimatedRe$BsReactNativeWeb.Timing;

var TimingXY = AnimatedRe$BsReactNativeWeb.TimingXY;

var Spring = AnimatedRe$BsReactNativeWeb.Spring;

var SpringXY = AnimatedRe$BsReactNativeWeb.SpringXY;

var Decay = AnimatedRe$BsReactNativeWeb.Decay;

var DecayXY = AnimatedRe$BsReactNativeWeb.DecayXY;

var Text = 0;

var Image = 0;

var View = 0;

var ScrollView = 0;

exports.Animation = Animation;
exports.CompositeAnimation = CompositeAnimation;
exports.Easing = Easing;
exports.Interpolation = Interpolation;
exports.Value = Value;
exports.ValueXY = ValueXY;
exports.$$event = $$event;
exports.delay = delay;
exports.sequence = sequence;
exports.parallel = parallel;
exports.stagger = stagger;
exports.loop = loop;
exports.createAnimatedComponent = createAnimatedComponent;
exports.Timing = Timing;
exports.TimingXY = TimingXY;
exports.Spring = Spring;
exports.SpringXY = SpringXY;
exports.Decay = Decay;
exports.DecayXY = DecayXY;
exports.Text = Text;
exports.Image = Image;
exports.View = View;
exports.ScrollView = ScrollView;
/* AnimatedRe-BsReactNativeWeb Not a pure module */
